"""migrate table homepageTable & infoTable

Revision ID: 8218a9a3af58
Revises: None
Create Date: 2022-08-06 22:13:04.288378

"""

# revision identifiers, used by Alembic.
revision = '8218a9a3af58'
down_revision = None

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepageTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('fund_type', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infoTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund', sa.String(), nullable=True),
    sa.Column('place_order_time', sa.DateTime(), nullable=True),
    sa.Column('conversion_fee', sa.Float(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infoTable')
    op.drop_table('homepageTable')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    op.execute("""INSERT INTO "homepageTable"(fund, company, fund_type, price, price_updated_at, create_at) values ('test_fund', 'test_company', 'test_fund_type', 10, '2022-08-06', current_timestamp)""")
    op.execute("""INSERT INTO "infoTable"(fund, place_order_time, conversion_fee, create_at) values ('test_fund', '2022-08-06', 0.01, current_timestamp)""")

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass